### ISSUE TITLE
Can't add any hosts to server registry

### ISSUE THREAD

**Issue by hackruu** [line/promgen#25]
Freshly installed promgen.
![promgen 2017-01-26 21-48-15](https://cloud.githubusercontent.com/assets/1213742/22345506/c7caf140-e419-11e6-9a19-252c4bb6c7fd.png)
![promgen 2017-01-26 21-48-27](https://cloud.githubusercontent.com/assets/1213742/22345510/ca4d2820-e419-11e6-8f94-d237dab2a7ed.png)
![sequel uniqueconstraintviolation at server_directory register 2017-01-26 21-49-07](https://cloud.githubusercontent.com/assets/1213742/22345520/cf6f6f0c-e419-11e6-98d8-4bcf9deea160.png)

my config.yml:
```
---
prometheus:
  url: http://127.0.0.1:9090/
db:
  logging: true
  dsn: sqlite://./db
config_writer:
  path: /tmp/prom.json
  notify:
    - http://localhost:9090/api/v1/config
rule_writer:
  rule_path: /tmp/prom.rule
  promtool_path: /usr/bin/promtool
  notify:
    - http://localhost:9090/api/v1/rule/
alert_senders:
  - module: Ikachan
    url: http://ikachan.localhost/
  - module: MailNotify
    smtp_server: smtp.localhost
  - module: Webhook
  - module: Alerta
    alerta_url: http://alerta.localhost
password: sea_monitoring
# Default Exporter Settings
# Examples from https://github.com/prometheus/prometheus/wiki/Default-port-allocations
default_exporters:
  node: 9100
  nginx: 9113
  mysqld: 9104
  apache: 9117
```

```
[ERROR] [Promgen] SQLite3::ConstraintException: columns type, params are not unique: INSERT INTO `server_directory` (`type`, `params`) VALUES ('Promgen::ServerDirectory::DB', '{}')
2017-01-26 18:48:31 - Sequel::UniqueConstraintViolation - SQLite3::ConstraintException: columns type, params are not unique:
	/usr/local/rvm/gems/ruby-2.3.3/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `step'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `block in each'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `loop'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `each'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `to_a'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:158:in `block in execute'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:95:in `prepare'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:134:in `execute'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/adapters/sqlite.rb:189:in `block (2 levels) in _execute'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/database/logging.rb:48:in `log_connection_yield'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/adapters/sqlite.rb:189:in `block in _execute'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/database/connecting.rb:251:in `synchronize'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/adapters/sqlite.rb:180:in `_execute'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/adapters/sqlite.rb:151:in `execute_insert'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/dataset/actions.rb:986:in `execute_insert'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sequel-4.35.0/lib/sequel/dataset/actions.rb:338:in `insert'
	/root/promgen/lib/promgen/repo/server_directory_repo.rb:49:in `insert'
	/root/promgen/lib/promgen/web/route/server_directory_route.rb:43:in `block in <class:Web>'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
10.250.250.43 - - [26/Jan/2017:18:48:31 +0000] "POST /server_directory/register HTTP/1.1" 500 574802 0.0531
```

**Comment by kfdm** [comment]
Ah, that page is typically only used for managing plugins. You should be able to go to the default page ( Example: http://localhost:8080/service/ ) and register a new Service. Under that, you can register a new Project, and Farms and Hosts are configured under there.
