### ISSUE TITLE
install docker-less

### ISSUE THREAD

**Issue by josefoSe** [line/promgen#293]
Hi !! 
Is there a way to install it on linux (ubuntu or redhat) without docker ??

**Comment by kfdm** [comment]
Yes, you should be able to install it using virtualenv similar to these instructions

https://github.com/line/promgen/blob/69cc1cbb366372ce42c988f7e426d8a2e13a96f0/CONTRIBUTING.md

**Comment by josefoSe** [comment]
first of all thanks for your time!
Could you tell me what version of Linux you have installed?
is to avoid incompatibilities

**Comment by kfdm** [comment]
I am currently using CentOS 7 but there is nothing that is distro specific. It should run equally fine on Debian based systems, and I do a lot of my development on MacOS with no issues.

**Comment by josefoSe** [comment]
Yes, buy i have a problem because the vine version of my ubuntu18 is too new and it crashes.
I'm not a pro in this thing...

**Comment by kfdm** [comment]
Are you installing it in a virtualenv?  Typically if you install it in a virtualenv, you shouldn't have issues with versions. Alternatively, if you run `make test` in the promgen directory, it will automatically setup a virtualenv and run the test cases to verify things there

**Comment by josefoSe** [comment]
installed on a centos7.4 as it says in: https://github.com/line/promgen/issues/34 
running promgen bootstrap does nothing:
-bash: promgen: command not found
do you have any idea what it could be?

**Comment by kfdm** [comment]
There are several steps in that guide that are not recommended. Can you try following this guide instead ?

https://github.com/line/promgen/blob/master/CONTRIBUTING.md#setting-up-promgen-for-development

**Comment by josefoSe** [comment]
Yes, I have tried by all means and always find a problem (incompatibility of versions in general). With docker, python - pip, etc. So I tried this tutorial which is very complete but it doesn't work either. It is very frustrating for me. Is there the possibility of accessing a virtual machine vmware, virtualbox or whatever where it is already working?

**Comment by kfdm** [comment]
Aye, getting (and giving) support is often quite frustrating (timezones and different countries often adds additional delays). To start with, I think I'm going to need more details if you would like me to help you. Can you give me detailed logs of the commands that you have run, and detailed logs of the output to your screen? 

Unfortunately, I don't have the resources to provide every combination of virtual machine, so for now the two methods I can reasonably support are the docker container or a virtualenv install.

**Comment by josefoSe** [comment]
Hello Paul, I am very grateful for your time, patience and knowledge. I send you the tests in a centos7. First with docker, then with pip, always following your guides..


`[root@centOs promgen]# docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap
/usr/src/app/promgen/__init__.py:30: UserWarning: Unset SECRET_KEY setting to random for now
  warnings.warn("Unset SECRET_KEY setting to random for now")
Bootstrapping Promgen
Creating promgen config /etc/promgen/promgen.yml from /usr/src/app/promgen/tests/examples/promgen.yml
Traceback (most recent call last):
  File "/usr/local/bin/promgen", line 11, in <module>
    load_entry_point('promgen', 'console_scripts', 'promgen')()
  File "/usr/src/app/promgen/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/promgen/management/commands/bootstrap.py", line 64, in handle
    shutil.copy(PROMGEN_CONFIG_DEFAULT, PROMGEN_CONFIG_FILE)
  File "/usr/local/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/etc/promgen/promgen.yml'
[root@centOs promgen]# 
`
Now with pip:

`(promgen) [root@centOs promgen]# promgen bootstrap
/etc/promgen/promgen/__init__.py:30: UserWarning: Unset SECRET_KEY setting to random for now
  warnings.warn("Unset SECRET_KEY setting to random for now")
Traceback (most recent call last):
  File "/etc/promgen/bin/promgen", line 11, in <module>
    load_entry_point('promgen', 'console_scripts', 'promgen')()
  File "/etc/promgen/promgen/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/etc/promgen/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/etc/promgen/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/etc/promgen/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/etc/promgen/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/etc/promgen/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/etc/promgen/lib/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/etc/promgen/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/etc/promgen/lib/python3.8/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/etc/promgen/lib/python3.8/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/etc/promgen/lib/python3.8/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/etc/promgen/lib/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/etc/promgen/lib/python3.8/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/etc/promgen/lib/python3.8/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/etc/promgen/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 66, in <module>
    check_sqlite_version()
  File "/etc/promgen/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
(promgen) [root@centOs promgen]# 
`

**Comment by josefoSe** [comment]
Hello Paul, I am very grateful to you for your time, knowledge and willingness to help me. I tell you that I had a significant advance by creating a promgen database and a promgen username and password. I guess it comes predefined somewhere like that. Of all the operating system options that I tried, the one I made the most progress was in Ubuntu 20.04 (also Centos7 and Ubuntu18.4).
With docker I got here:
`root@ubuntu02:/home/patrol/promgen# docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap
Traceback (most recent call last):
  File "/usr/local/bin/promgen", line 11, in <module>
    load_entry_point('promgen', 'console_scripts', 'promgen')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/src/app/promgen/__init__.py", line 23, in <module>
    envdir.open(PROMGEN_CONFIG_DIR)
  File "/usr/local/lib/python3.6/site-packages/envdir/runner.py", line 50, in open
    return Env(self.path(path))
  File "/usr/local/lib/python3.6/site-packages/envdir/env.py", line 36, in __init__
    self._load()
  File "/usr/local/lib/python3.6/site-packages/envdir/env.py", line 73, in _load
    value = self._get(name)
  File "/usr/local/lib/python3.6/site-packages/envdir/env.py", line 89, in _get
    return var.read().strip('\n').replace('\x00', '\n')
  File "/usr/local/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 16: invalid continuation byte
`

**Comment by josefoSe** [comment]
I already have it working on my ubuntu 20.04 desktop. Now I will have to learn how it works and how to configure it. The two obstacles I had were:
-You have to have a promgen user / password and a promgen database intensity
-with pip uninstall vine 5.0 and install version 1.3.0
thank you very much!!

**Comment by kfdm** [comment]
Thanks for the closing notes. I should probably audit the install directions and make sure some of the user and database requirements are a bit more clear. 🙇
