### ISSUE TITLE
docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap   have error  

### ISSUE THREAD

**Issue by liublcom** [line/promgen#301]
hi:
i have run the command docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap,
then i put the mysql driver mysql://prome:Prome2020@10.0.184.106/prome when the system recommend to put DATABASE_URL,the last the system have this error :Running django system checks
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
self.connect()
File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
self.connection = self.get_new_connection(conn_params)
File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 194, in get_new_connection
conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file

i have use mysql driver,the error has tell me the current database is sqlite3

**Comment by liublcom** [comment]
i have re-install the docker ,this error don't appear。
