### ISSUE TITLE
docker-compose run web createsuperuser failed

### ISSUE THREAD

**Issue by like-inspur** [line/promgen#85]
I use docker-compose up -d to create promgen service, it works well. But when I execute docker-compose run web createsuperuser, mysql outputs error like this:
[root@registry promgen]# docker-compose run web createsuperuser
Starting promgen_mysql_1 ... done
Starting promgen_redis_1 ... done

You have 25 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, promgen, sessions, sites, social_django.
Run 'python manage.py migrate' to apply them.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'promgen.auth_user' doesn't exist")

I use myql 5.5 in docker-compose,yaml, the output of docker-compose is like this:
[root@registry promgen]# docker-compose ps
promgen_alertmanager_1   /bin/alertmanager --config ...   Up       0.0.0.0:9093->9093/tcp
promgen_base_1           /docker-entrypoint.sh sh - ...   Exit 1                         
promgen_blackbox_1       /bin/blackbox_exporter --c ...   Up       9115/tcp              
promgen_mysql_1          docker-entrypoint.sh mysqld      Up       3306/tcp              
promgen_prometheus_1     /bin/prometheus --config.f ...   Up       0.0.0.0:9090->9090/tcp
promgen_redis_1          docker-entrypoint.sh redis ...   Up       6379/tcp              
promgen_web_1            /docker-entrypoint.sh prom ...   Up       0.0.0.0:8080->8000/tcp
promgen_worker_1         /docker-entrypoint.sh work ...   Up       8000/tcp

**Comment by kfdm** [comment]
This error suggests that the database may not have been initialized yet
```_mysql_exceptions.ProgrammingError: (1146, "Table 'promgen.auth_user' doesn't exist")```
Could you try running this to create the databases?
```docker-compose run web migrate```
I may need to check the README to see if it's missing some instructions.
