### ISSUE TITLE
How do I begin the installation from scratch?

### ISSUE THREAD

**Issue by dxz6228** [line/promgen#86]
Hello.
I tried to get promgen installed yesterday, but should've looked ahead in the readme, because when I started the process I didn't have MySQL or Redis. Well, did the MySQL part, but ran out of time, and so had no broker url to pass to the installation, and I had the smart idea of Ctrl+C'ing out of it, expecting that if I just do `sudo docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen bootstrap` again tomorrow, it'll work.
Nope. Now it spits out a gigantic nasty stack trace to me, so I think I broke a lot of things. Help?
Stack trace in question:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2002, 'Can\'t connect to local MySQL server through socket \'/run/mysqld/mysqld.sock\' (2 "No such file or directory")')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/promgen", line 11, in <module>
    load_entry_point('promgen', 'console_scripts', 'promgen')()
  File "/usr/src/app/promgen/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.5/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1284, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1359, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 913, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 219, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 322, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/validation.py", line 49, in check_field
    field_type = field.db_type(self.connection)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 644, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 174, in data_types
    if self.features.supports_microsecond_precision:
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/features.py", line 53, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 385, in mysql_version
    with self.temporary_connection() as cursor:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 591, in temporary_connection
    cursor = self.cursor()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, 'Can\'t connect to local MySQL server through socket \'/run/mysqld/mysqld.sock\' (2 "No such file or directory")')

**Comment by kfdm** [comment]
The settings files should be in ~/.config/promgen so the first check would be to look what's set in there. If you want to re-run the bootstrap, you could delete that directory and then start again.

**Comment by dxz6228** [comment]
Oh, okay! I thought it'd be harder than that.

**Comment by dxz6228** [comment]
Actually, as an addendum. So the bootstrap worked after that, but now it's the `sudo docker run --rm -v ~/.config/promgen:/etc/promgen/ line/promgen migrate` and `sudo docker run --rm -it -v ~/.config/promgen:/etc/promgen/ line/promgen createsuperuser` that spit out pretty much the same stack trace to me.
I've edited the .yml config file to set the right URLs for Prometheus and Alert Manager, by the way.
Ran promgen via `docker run --rm -p 8000:8000 -v ~/.config/promgen:/etc/promgen/ line/promgen` despite errors. Hey, it started! But it's showing the internal error page, so obviously something isn't right.
What do?

**Comment by dxz6228** [comment]
Disregard, we worked through it. The problem was that I put localhost instead of 127.0.0.1 as addressed for MySQL and Redis.
Now I'm just having an internal error to deal with. Ain't that an improvement. :)

**Comment by dxz6228** [comment]
By the way, docker-compose, when run from the cloned root directory of the project, gives

ERROR: Service 'base' failed to build: The command '/bin/sh -c SECRET_KEY=1 promgen collectstatic --noinput' returned a non-zero code: 1

Just a heads up.

**Comment by dxz6228** [comment]
Okay, so here's an extended update.

We managed to get through the bootstrap and migrations and whatnot.
Problem 1. Not very clear whether the web worker and celery worker are "one or the other" or we need both. Regardless, if only web worker is up, it gives us the internal error page. Trying to start the celery worker blocks the bash, with no output.
And as mentioned earlier, trying to use docker-compose results in an error near the end of the build.

Please advise.

**Comment by kfdm** [comment]
Sorry for the long delay.

I tried to test this on my local machine and got similar mysql errors. When I tried to debug, it looked like mysql was not currently running. When I tried to get mysql running, it seemed like I was getting some other errors, but it seemed to work after I cleared out `docker/mysql_data` and then tried running with `image: mysql:5.7`. Could you try that and see if that makes a difference ?

Admittedly I do not use docker-compose myself very much (I deploy out of a virtualenv) so I'm often a bit confused on the best practices and in debugging errors.

As for the confusion between *web worker* and *celery worker* this is something I really need to fix in the documentation. Sorry for the confusion :(

**Comment by linbo** [comment]
Hi,

Can I deploy it without docker?

**Comment by kfdm** [comment]
@linbo 
Docker is not required. If you look at [CONTRIBUTING.md](https://github.com/line/promgen/blob/master/CONTRIBUTING.md#setting-up-promgen-for-development) the instructions for deploying with a Python virtualenv are listed there.

**Comment by linbo** [comment]
@kfdm Thanks.
